### ISSUE TITLE
Algoritmo de Karatsuba

### ISSUE THREAD

**Issue by dpkg-i-foo-deb** [dpkg-i-foo-deb/proyecto-analisis-algoritmos#58]
Emmm, implementar esa cosa como dios le ayude

**Comment by StivenHerreraSierra** [comment]
**Recursos:**

- Implementación: https://www.geeksforgeeks.org/karatsuba-algorithm-for-fast-multiplication-using-divide-and-conquer-algorithm

- Explicación: https://www.youtube.com/watch?v=4Q3g8j4TD7c
